#!/bin/sh

#script created by James Jara (google codes)

#url
url='http://gadget.citasyrefranes.com/gadget_xml.php?t=PI&r=83'

#get data
data=` wget -q -O - $url | sed -n -e 's/.*<texto>\(.*\)<\/texto>.*/\1/p'`

#create notification
notify-send "Frase Piropo" "${data}"
